//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printajmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int idComment { get; set; }
        public string idUser { get; set; }
        public int idTiskarna { get; set; }
        public string comment { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> parrentID { get; set; }
        public string name { get; set; }
        public string img { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tiskarne tiskarne { get; set; }
    }
}
