//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printajmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ratings
    {
        public int idRating { get; set; }
        public string idUser { get; set; }
        public int idTiskarna { get; set; }
        public int rating { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tiskarne tiskarne { get; set; }
    }
}
