//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printajmo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiskarne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tiskarne()
        {
            this.Comments = new HashSet<Comments>();
            this.ratings = new HashSet<ratings>();
        }
    
        public int idtiskarne { get; set; }
        public string naziv { get; set; }
        public Nullable<decimal> a4cb { get; set; }
        public Nullable<decimal> a4barvno { get; set; }
        public Nullable<decimal> a4cboboje { get; set; }
        public Nullable<decimal> a4barvnooboje { get; set; }
        public string ulica { get; set; }
        public Nullable<int> postnast { get; set; }
        public string mesto { get; set; }
        public string email { get; set; }
        public string telefonska { get; set; }
        public string dodatno { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string lastnik { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<int> voteNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ratings> ratings { get; set; }
    }
}
